Gear/ViewModels/PaymentViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Gear.ViewModels
{
    public class PaymentViewModel
    {
    }
}

Gear/ViewModels/ReceiptViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Gear.Models;


namespace Gear.ViewModels
{
    public class ReceiptViewModel
    {
        public Receipt receipt { get; set; }
        public List<PaymentType> paymentType { get; set; }
    }
}

Gear/ViewModels/SearchViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Gear.Models;

namespace Gear.ViewModels
{
    public class SearchViewModel
    {
        public List<Game> View { get; set; }
        public Cart Cart { get; set; }
        public List<Genre> Tags { get; set; }

        public string Selected { get; set; }
        public string Search { get; set; }
    }
}

Gear/ViewModels/StoreViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Gear.Models;

namespace Gear.ViewModels
{
    public class StoreViewModel
    {
        public List<Game> Showcase { get; set; }

        public List<Game> Popular { get; set; }
        public List<Discount> Discounted { get; set; }
        public List<Game> Newest { get; set; }
        public Cart Cart { get; set; } 
    }
}

Gear/Controllers/GameController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Gear.Models;



using System.Threading.Tasks;
using System.Net.Http;
using Newtonsoft.Json;
using System.Net.Http.Headers;
using System.Net;
using Newtonsoft.Json.Linq;

/// <summary>
/// Tadas Kalvaitis
/// </summary>
namespace Gear.Controllers
{
    public class GameController : ControllerBase
    {

        //GearDBEntities db = new GearDBEntities();

        // GET: GamePage
        public ActionResult Index(int id)
        {
            Game gameInfo = db.Games.Where(g => g.Id.Equals(id)).ToList()[0];
            int devId = gameInfo.Developer_Id;
            Developer dev = db.Developers.Where(d => d.Id == devId).ToList()[0];

            Game ga = db.Games.ToList().Where(game => game.Id.Equals(gameInfo.Id)).ToList()[0];
            List<Genre> genres = ga.Genres.ToList();
            List<Discount> discounts = ga.Discounts.Where(d => d.ExpireDate > DateTime.Now).ToList();

            List<Game> allGames = db.Games.ToList();

            List<Game> recomended = RecomendedGames(genres, allGames, gameInfo);

            List<Comment> com = ga.Comments.ToList();

            double price = gameInfo.Price;
            foreach (var item in discounts)
            {
                price *= item.Modifier;
            }

            TwitchStreamers streamer = getTwitchStreamer(gameInfo.Name);
            
            User user = null;
            if ((bool)Session["LoggedIn"])
            {
                string logedIn = Session["Username"].ToString();
                user = db.Users.Where(u => u.Username.Equals(logedIn)).ToList()[0];
            }
               

            if (streamer != null)
            {
                Game game = new Game()
                {
                    Streamer = streamer.channel.display_name,

                    Id = gameInfo.Id,
                    Name = gameInfo.Name,
                    Description = gameInfo.Description,
                    Dir = gameInfo.Dir,
                    Developer = dev,
                    ReleaseDate = gameInfo.ReleaseDate,
                    Price = price,
                    GameRatings = db.GameRatings.Where(g => g.Game_Id == gameInfo.Id).ToList(),
                    Genres = genres,
                    TrailerURL = gameInfo.TrailerURL,
                    Recomended = recomended,
                    User = user,
                    Comments = com
                    
            };
                return View(game);
            }

            else
            {
                var game = new Game()
                {
                    Id = gameInfo.Id,
                    Name = gameInfo.Name,
                    Description = gameInfo.Description,
                    Dir = gameInfo.Dir,
                    Developer = dev,
                    ReleaseDate = gameInfo.ReleaseDate,
                    Price = price,
                    GameRatings = db.GameRatings.Where(g => g.Game_Id == gameInfo.Id).ToList(),
                    Genres = genres,
                    TrailerURL = gameInfo.TrailerURL,
                    Recomended = recomended,
                    User = db.Users.Where(u => u.Username.Equals(user)).ToList()[0],
                    Comments = com
                };
                return View(game);
            }


        }

        public ActionResult AgeValidation(int id)
        {
            var gameInfo = db.Games.Where(g => g.Id.Equals(id)).ToList()[0];

            User user = null;
            if ((bool)Session["LoggedIn"])
            {
                string logedIn = Session["Username"].ToString();
                user = db.Users.Where(u => u.Username.Equals(logedIn)).ToList()[0];
            }

            var game = new Game()
            {
                Id = gameInfo.Id,
                Name = gameInfo.Name,
                Dir = gameInfo.Dir,
                AgeRestriction = gameInfo.AgeRestriction,
                User = user
            };
            return View(game);
        }



        public TwitchStreamers getTwitchStreamer(string name)
        {
            var webClient = new WebClient();
            webClient.Headers.Add("Client-ID", "9biq0mp63j7qbe0pv8x3sugesx1ezr");

            var json = webClient.DownloadString(@"https://api.twitch.tv/kraken/streams?game=" + name);

            var contentJo = (JObject)JsonConvert.DeserializeObject(json);
            var streamersJArray = contentJo["streams"].Value<JArray>();

            var rez = streamersJArray.ToObject<List<TwitchStreamers>>();

            List<TwitchStreamers> enStreamers = new List<TwitchStreamers>();

            foreach (var item in rez)
                if (item.channel.language == "en")
                    enStreamers.Add(item);

            Random rand = new Random();


            int stream = -1;
            if (enStreamers != null && enStreamers.Count > 0)
                stream = rand.Next(0, enStreamers.Count);


            if (stream != -1)
                return enStreamers[stream];
            else
                return null;
        }

        public List<Game> RecomendedGames(List<Genre> tags, List<Game> allGames, Game currentGame)
        {
            List<Game> recomended = new List<Game>();
            foreach(var item in allGames)
            {
                if (item != currentGame)
                {
                    List<Genre> genres = item.Genres.ToList();
                    foreach (var gen in genres)
                    {
                        if (tags.Contains(gen))
                        {
                            recomended.Add(item);
                            break;
                        }
                    }
                }
            }
            
            if (recomended.Count <= 5)
            {
                foreach (var item in recomended)
                {
                    List<Discount> discounts = item.Discounts.Where(d => d.ExpireDate > DateTime.Now).ToList();
                    item.Discount = 0;
                    foreach (var disc in discounts)
                    {
                        item.Price *= disc.Modifier;
                        item.Discount = item.Discount + (disc.Modifier * 100);
                    }
                }
                return recomended;
            }
            else
            {
                Random ran = new Random();
                int n = 0;
                List<Game> pickedGames = new List<Game>();
                while (pickedGames.Count != 5)
                {
                    n = ran.Next(0, recomended.Count);
                    pickedGames.Add(recomended[n]);
                    recomended.Remove(recomended[n]);
                }

                foreach (var item in pickedGames)
                {
                    List<Discount> discounts = item.Discounts.Where(d => d.ExpireDate > DateTime.Now).ToList();
                    item.Discount = 0;
                    foreach (var disc in discounts)
                    {
                        item.Price *= disc.Modifier;
                        item.Discount += (int)disc.Modifier * 100;
                    }
                }

                return pickedGames;
            }
        }

        [HttpPost]
        public ActionResult Index(string note, int id, string coment, int? rating, string addToCart)
        {
            string logedInUser = Session["Username"].ToString();
            User user = db.Users.Where(u => u.Username.Equals(logedInUser)).ToList()[0];

            //User user = Session["User"] as User;
            if (note != null)
            {
                db.Marks.Add(new Mark()
                {
                    CreateDate = DateTime.Now,
                    Description = note,
                    Game_Id = id,
                    User_Username = user.Username
                });
            }
            else if (coment != null || rating != null)
            {
                if (coment != "")
                {
                    db.Comments.Add(new Comment()
                    {
                        CreateDate = DateTime.Now,
                        Content = coment,
                        Game_Id = id,
                        User_Username = user.Username
                    });
                }
               


                if (rating != null)
                {
                    var currentGameRating = db.GameRatings.SingleOrDefault(gr => gr.User_Username.Equals(user.Username) && gr.Game_Id.Equals(id));
                    var currentGameComents = user.Comments.Where(c => c.Game_Id.Equals(id)).ToList();
                    if (currentGameRating != null)
                    {
                        currentGameRating.CreateDate = DateTime.Now;
                        currentGameRating.Rating = (int)rating;
                        // update rating in db (magic)
                    }
                    else if (coment != "" || currentGameComents.Count != 0)
                    {
                        db.GameRatings.Add(new GameRating()
                        {
                            CreateDate = DateTime.Now,
                            Rating = (int)rating,
                            Game_Id = id,
                            User_Username = user.Username
                        });
                    }
                }
            }
            else if (addToCart != null)
            {
                var cart = db.Carts.Where(c => c.User_Username.Equals(user.Username)).Where(c=>c.Receipts.Count == 0).FirstOrDefault();

                if (cart == null)
                {
                    cart = new Cart()
                    {
                        CreateDate = DateTime.Now,
                        EditDate = DateTime.Now,
                        User_Username = user.Username
                    };

                    db.Carts.Add(cart);
                    db.SaveChanges();

Gear/Controllers/StoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Gear.Models;
using Gear.ViewModels;

/// <summary>
/// Domantas Banionis
/// </summary>
namespace Gear.Controllers
{
    public class StoreController : ControllerBase
    {
        // GET: Store
        public ActionResult Index()
        {
            DateTime now = DateTime.Now;

            List<Game> popular = db.Games.OrderByDescending(
                    g => g.Visits.Where(v => v.Game_Id == g.Id)
                    .Sum(x => x.Amount)).Take(10).ToList();
            List<Game> newest = db.Games.Where(
                    g => g.ReleaseDate < now)
                    .OrderByDescending(g => g.ReleaseDate).Take(10).ToList();
            List<Discount> discounted = db.Discounts.Where(
                    d => d.ExpireDate > now).Where(d => d.Hidden != 1).Take(10).ToList();

            Random rand = new Random();
            List<Game> showcase = db.Games.OrderByDescending(
                    g => g.GameRatings.Where(r => r.Game_Id == g.Id)
                    .Sum(x => x.Rating)).Take(6).ToList();

            string user = (string)Session["Username"];
            Cart cart = (bool)Session["LoggedIn"] == true ? db.Carts.Where(c => c.User_Username.Equals(user)).Where(c => c.Receipts.Count == 0).FirstOrDefault() : null;

            StoreViewModel model = new StoreViewModel()
            {
                Popular = popular,
                Discounted = discounted,
                Newest = newest,
                Showcase = showcase,
                Cart = cart
            };
            return View(model);
        }

        public ActionResult Search(string search, string tag)
        {
            search = search == null ? "" : search;

            List<Game> show = db.Games.Where(g => g.Name.Contains(search)).OrderBy(g=>g.Name).ToList();
            List<Genre> genre = db.Genres.ToList();

            string user = (string)Session["Username"];
            Cart cart = (bool)Session["LoggedIn"] == true ? db.Carts.Where(c => c.User_Username.Equals(user)).Where(c => c.Receipts.Count == 0).FirstOrDefault() : null;

            if (tag != null)
            {
                show = show.Where(s=>s.Genres.Where(g=>g.Name == tag).FirstOrDefault() != null).ToList();
            }

            SearchViewModel model = new SearchViewModel() {
                View = show,
                Cart = cart,
                Tags = genre,
                Selected = tag,
                Search = search
            };

            return View(model);
        }

        //cart
        [HttpGet]
        public ActionResult Payment()
        {
            string user = (string)Session["Username"];
            Cart cart = db.Carts.Where(c => c.User_Username.Equals(user)).Where(c => c.Receipts.Count() == 0).FirstOrDefault();

            return View(cart);
        }

        //receipt
        [HttpGet]
        public ActionResult Receipt(int? cartId)
        {
            if (cartId == null)
            {
                return RedirectToAction("Payment");
            }

            Cart userCart = db.Carts.Where(c=>c.Id == (int)cartId).SingleOrDefault();

            if (userCart == null)
            {
                return RedirectToAction("Payment");
            }


            DateTime now = DateTime.Now;
            double total = 0;

            foreach (CartItem item in userCart.CartItems)
            {
                Discount discount = item.Game.Discounts.Where(d => d.ExpireDate > now).Where(d => d.Hidden != 1).FirstOrDefault();

                if (discount != null)
                {
                    total += item.Amount * item.Game.Price * discount.Modifier;
                }
                else
                {
                    total += item.Amount * item.Game.Price;
                }
            }

            Receipt receipt = new Receipt() { Cart_Id = userCart.Id, CreateDate = DateTime.Now, Total = total };
            db.Receipts.Add(receipt);
            db.SaveChanges();

            List<PaymentType> paymentType = db.PaymentTypes.ToList();

            return View(new ReceiptViewModel() { receipt = receipt, paymentType = paymentType });
        }

        public ActionResult RemoveFromCart(int id)
        {
            CartItem item = db.CartItems.Where(c => c.Id == id).SingleOrDefault();
            db.CartItems.Remove(item);
            db.SaveChanges();

            return RedirectToAction("Payment");
        }

        public ActionResult ChangeCartItemAmount(int id, int amount)
        {
            if (amount <= 0)
            {
                return RedirectToAction("RemoveFromCart",new { id = id });
            }
            CartItem item = db.CartItems.Where(c => c.Id == id).SingleOrDefault();

            if (item.Amount == amount)
            {
                return RedirectToAction("Payment");
            }

            item.Amount = amount;
            db.SaveChanges();

            return RedirectToAction("Payment");
        }

        public ActionResult paidForItems(int cartId)
        {
            string username = (string)Session["Username"];
            User usr = db.Users.Where(u=>u.Username.Equals(username)).FirstOrDefault();

            if (usr != null)
            {
                Cart cart = db.Carts.Where(c => c.Id == cartId).FirstOrDefault();
                if (cart != null && cart.CartItems.Count > 0)
                {
                    foreach (CartItem item in cart.CartItems)
                    {
                        LibraryGame libgame = usr.LibraryGames.Where(l=>l.Game_Id == item.Game_Id).FirstOrDefault();
                        if (libgame == null)
                        {
                            usr.LibraryGames.Add(new LibraryGame() { CreateDate = DateTime.Now, Game_Id = item.Game_Id, LastOpen = DateTime.Now, PlayTime = TimeSpan.Zero, User_Username = usr.Username });
                        }
                        else
                        {
                            //code to give codes
                        }
                    }
                }
            }

            db.SaveChanges();

            return RedirectToAction("Index","Profile");
        }
    }
}

Gear/Views/Store/Payment.cshtml
@model Gear.Models.Cart
@{
                /**/

                ViewBag.Title = "Payment";
    }
<h5 class="display-4 mt-2">Payment</h5>
<hr />

@if (Model != null && Model.CartItems.Count > 0)
{
    <div class="row">
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th scope="col">Title</th>
                    <th class="text-center" scope="col">Amount</th>
                    <th class="text-center" scope="col">Price</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (Gear.Models.CartItem item in Model.CartItems)
                {
                    <tr class="">
                        <td><span class="d-block">@item.Game.Name</span></td>

                        <td class="text-center">
                            @using (Html.BeginForm("ChangeCartItemAmount", "Store", FormMethod.Post))
                            {
                                <input type="text" value="@(item.Id)" name="id" class="d-none"/>
                                <input class="text-center" value="@(item.Amount)" name="amount" onchange="this.form.submit()">
                            }
                        </td>
                        @{
                            DateTime now = DateTime.Now;
                            Gear.Models.Discount hasDiscount = item.Game.Discounts.Where(d => d.ExpireDate > now).Where(d => d.Hidden != 1).FirstOrDefault();
                        }
                        @if (hasDiscount != null)
                        {
                            <td>
                                <span class="d-block text-center badge badge-success">-@hasDiscount.Modifier.ToString("#0.##%")</span>
                                <span class="d-block text-center badge badge-light">@(((item.Game.Price * hasDiscount.Modifier) * item.Amount).ToString("0.00")) EUR</span>
                            </td>
                        }
                        else
                        {
                            <td><span class="d-block text-center badge badge-light">@(item.Game.Price * item.Amount) EUR</span></td>
                        }
                        <td>@Html.ActionLink("X", "RemoveFromCart", "Store", new { id = item.Id }, new { @class = "btn btn-sm btn-danger" })</td>
                    </tr>
                }
            </tbody>
        </table>

        <a class="btn btn-primary ml-auto" href="@(Url.Action("Receipt","Store",new { cartId = Model.Id }))"> Order</a>
    </div>
}
else
{
    <div class="row jumbotron">
        <h1 class="display-4">Cart is empty!</h1>
    </div>
}

Gear/Views/Store/Receipt.cshtml
@model Gear.ViewModels.ReceiptViewModel
@{
    ViewBag.Title = "Payment";
}


@if (Model != null)
{
    <div class="row">
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th scope="col">Title</th>
                    <th class="text-center" scope="col">Amount</th>
                    <th class="text-center" scope="col">Price</th>
                </tr>
            </thead>
            <tbody>
                @foreach (Gear.Models.CartItem item in Model.receipt.Cart.CartItems)
                {
                    <tr class="">
                        <td><span class="d-block">@item.Game.Name</span></td>
                        <td><span class="d-block text-center">@item.Amount</span></td>
                        @{
                            DateTime now = DateTime.Now;

                            Gear.Models.Discount hasDiscount = item.Game.Discounts.Where(d => d.ExpireDate > Model.receipt.CreateDate).Where(d => d.Code.Equals("GLOBAL")).FirstOrDefault();
                        }
                        @if (hasDiscount != null)
                        {
                            <td>
                                <span class="d-block text-center badge badge-success">-@hasDiscount.Modifier.ToString("#0.##%")</span>
                                <span class="d-block text-center badge badge-light">@(((item.Game.Price * hasDiscount.Modifier) * item.Amount).ToString("0.00")) EUR</span>
                            </td>
                        }
                        else
                        {
                            <td><span class="d-block text-center badge badge-light">@(item.Game.Price * item.Amount) EUR</span></td>
                        }
                    </tr>
                }
            </tbody>
        </table>
        @*@Url.Action("", "Store",new { cart = Model.Id })*@
        <b>Total: @Model.receipt.Total.ToString("0.00") EUR</b>
        <div class="ml-auto">
           
            <select class="custom-select-sm">
                @foreach (Gear.Models.PaymentType type in Model.paymentType)
                {
                    <option value="@type.Id">@type.Name</option>
                }
            </select>
            <a class="btn btn-primary" href="@(Url.Action("paidForItems","Store",new { cartId = Model.receipt.Cart_Id,  }))">Pay</a>
        </div>
    </div>
}
else
{
    <div class="row jumbotron">
        <h1 class="display-4">Receipt doesnt exist!</h1>
    </div>
}

Gear/Views/Store/Search.cshtml
@{
    ViewBag.Title = "Search";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model Gear.ViewModels.SearchViewModel
<div class="row mt-2">
    <h5 class="display-4">Search</h5>
</div>
<hr/>
<div class="row">
    <div>
        <span>Search: </span>
        <b>@(Model.Search == "" ? "All" : Model.Search)</b>
    </div>
    @if (Model.Selected != null)
    {
        <div class="ml-2">
            <span>Category: </span>
            <b>@Model.Selected</b>
        </div>
    }
</div>
<div class="row mt-3">
    <div class="col-9">
        @if (Model.View.Count > 0)
        {
            foreach (Gear.Models.Game game in Model.View)
            {
                <div class="row border-bottom p-sm-1 rounded">
                    <div class="col-3">
                        <a href="@Url.Action("AgeValidation","Game",new { id = game.Id })">
                            <img class="p-0 rounded img-fluid" style="width: 100%; height:auto;" src="@("../Files/" + game.Dir + "/icon.jpg")" alt="First slide">
                        </a>
                    </div>
                    <div class="col row w-100">
                        <div class="col row mr-auto">
                            <div class="align-self-start col-12 p-0">
                                <h5>@Html.ActionLink(game.Name, "AgeValidation", "Game", new { id = game.Id }, new { @class = "text-dark" })</h5>
                                <text class="">@game.ShortDescription</text>
                            </div>
                            <div class="align-self-end">
                                @foreach (Gear.Models.Genre genre in game.Genres)
                                {
                                    @Html.ActionLink(genre.Name, "Search", "Store", new { tag = genre.Name }, new { @class = "badge badge-info ml-sm-1" })
                                }
                            </div>
                        </div>
                        <div class="col-auto align-self-center mr-2">
                            @{
                                DateTime now = DateTime.Now;
                                Gear.Models.Discount hasDiscount = game.Discounts.Where(d => d.ExpireDate > now).Where(d => d.Hidden != 1).FirstOrDefault();
                            }

                            @if (hasDiscount != null)
                            {
                                <span class="d-block text-center badge badge-success">-@hasDiscount.Modifier.ToString("#0.##%")</span>
                                <span class="d-block text-center badge badge-light">@((game.Price * hasDiscount.Modifier).ToString("0.00")) EUR</span>
                            }
                            else
                            {
                                <span class="d-block text-center badge badge-light">@game.Price EUR</span>
                            }
                        </div>
                    </div>
                </div>
            }
        }
        else
        {
            <div class="row jumbotron">
                <h1 class="display-4">No results!</h1>
            </div>
        }
    </div>

    @using (Html.BeginForm("Search", "Store", FormMethod.Post, new { @class = "col nav navbar-nav ml-1" }))
    {
        <div class="nav-item input-group mb-1">
            <input type="text" class="form-control text-truncate" placeholder="Search store" name="search">
            <div class="input-group-append">
                <button class="btn btn-outline-secondary" type="submit">Search</button>
            </div>
        </div>
        if ((bool)Session["LoggedIn"])
        {
            <div class="nav-item">
                <button class="btn btn-light w-100" type="button" data-toggle="collapse" data-target="#cartCollapse" aria-expanded="false" aria-controls="cartCollapse"><b>Cart</b></button>
                <div class="collapse multi-collapse" id="cartCollapse">
                    <div class="dropdown-divider"></div>
                    <a href="@Url.Action("Payment","Store")" class="btn btn-outline-info w-100">Checkout</a>
                    <div class="dropdown-divider"></div>
                    <ul class="list-group">
                        @if (Model.Cart != null && Model.Cart.CartItems.Count != 0)
                        {
                            foreach (Gear.Models.CartItem item in Model.Cart.CartItems)
                            {
                                <li class="list-group-item">
                                    <span class="text-primary">x@(item.Amount)</span>
                                    <span class="text-capitalize">@item.Game.Name</span>
                                </li>
                            }
                        }
                        else
                        {
                            <li class="list-group-item alert alert-info text-center">Cart is empty!</li>
                        }
                    </ul>
                </div>
            </div>
        }

        <div class="nav-item text-center">
            <button class="btn btn-light w-100" type="button" data-toggle="collapse" data-target="#tagCollapse" aria-expanded="false" aria-controls="tagCollapse"><b>Categories</b></button>
            <div class="collapse multi-collapse" id="tagCollapse">
                <div class="dropdown-divider"></div>
                @if (Model.Tags != null && Model.Tags.Count > 0)
                {
                    <div class="btn-group-toggle" data-toggle="buttons">
                        @foreach (Gear.Models.Genre item in Model.Tags)
                        {
                            <label class="btn btn-sm btn-warning">
                                <input type="radio" name="tag" value="@item.Name"> @item.Name
                            </label>
                        }
                    </div>
                }
                else
                {
                    <div class="list-group-item alert alert-info text-center">No categories!</div>
                }
            </div>
        </div>
    }
</div>